# default config
# chatcolors 0-9 are equal to normal mc chat colors, 10=a, 11=b, 12=c, 13=d, 14=e, 15=f
ingameconfigurable:
  adminchatcolor: 11
  partychatcolor: 10
  staffnamechatcolor: 15
  playernamechatcolor: 15

# players that are frozen, and left that way
frozen:
partychatslist:
  - Paxs_Nation
  - Bandits_bandits

partychats:
  Paxs_Nation:
    owner: Paxination
    password: dc9285
    members: ''

  Bandits_bandits:
    owner: Bandityogo
    password: ''
    members: ''